name: Dependabot PR Check

on:
  pull_request:
    # Run only on Dependabot PRs
    # The if condition is handled in the job

jobs:
  dependabot-check:
    name: Dependabot PR Check
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'
        cache: true
    
    - name: Install dependencies
      run: go mod download
    
    - name: Verify dependencies
      run: |
        echo "Verifying go.mod and go.sum consistency..."
        go mod verify
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "go.mod or go.sum has uncommitted changes"
          git diff
          exit 1
        fi
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Quick security scan
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        # G204: Subprocess launched with variable - false positive for test helpers
        # G103: unsafe.Pointer usage - false positive for performance-critical hashing
        # G115: integer overflow - false positive due to proper bounds checking
        # G404: weak random - false positive for performance profiler
        # G304: file inclusion - false positive due to path validation implemented
        gosec -exclude=G204,G103,G115,G404,G304 -quiet ./...
    
    - name: Comment on PR
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('Dependabot PR Check')
          );
          
          const status = '${{ job.status }}';
          const message = status === 'success' 
            ? '✅ **Dependabot PR Check passed!** All tests and security scans completed successfully.'
            : '❌ **Dependabot PR Check failed!** Please review the logs for details.';
          
          const body = `## 🤖 Dependabot PR Check\n\n${message}\n\n*This comment was automatically generated by the Dependabot workflow.*`;
          
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          } 