name: Pull Request Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'
        cache: true
    
    - name: Install dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run go fmt check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted. Please run 'go fmt ./...'"
          gofmt -s -d .
          exit 1
        fi
    
    - name: Install and run staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
    
    - name: Quick security scan
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        # G204: Subprocess launched with variable - false positive for test helpers
        # G103: unsafe.Pointer usage - false positive for performance-critical hashing
        # G115: integer overflow - false positive due to proper bounds checking
        # G404: weak random - false positive for performance profiler
        # G304: file inclusion - false positive due to path validation implemented
        gosec -exclude=G204,G103,G115,G404,G304 -quiet ./... 