name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'
    
    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest
    
    - name: Run gosec with exclusions
      run: |
        # Run gosec excluding known false positives
        # G204: Subprocess launched with variable - false positive for test helpers
        # G103: unsafe.Pointer usage - false positive for performance-critical hashing
        # G115: integer overflow - false positive due to proper bounds checking
        # G404: weak random - false positive for performance profiler
        # G304: file inclusion - false positive due to path validation implemented
        gosec -exclude=G204,G103,G115,G404,G304 ./...
      
    - name: Run gosec for remaining issues only
      run: |
        # Run a second pass to show only the issues we care about
        echo "=== Security Scan Results ==="
        echo "Excluded rules (false positives):"
        echo "- G204: Subprocess launched with variable (test helpers)"
        echo "- G103: unsafe.Pointer usage (performance-critical hashing)"
        echo "- G115: integer overflow (proper bounds checking implemented)"
        echo "- G404: weak random (performance profiler context)"
        echo "- G304: file inclusion (path validation implemented)"
        echo ""
        echo "Remaining issues:"
        gosec -exclude=G204,G103,G115,G404,G304 -fmt=text ./... 